[package]
name = "statsd_client"
version = "0.2.1"
authors = ["Julian Squires <julian@cipht.net>", "Francis Lalonde <francis.lalonde@adgear.com>"]
publish = false

[dependencies]
time = "0.1"

[features]
bench = []
